# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

remote_theme: "mmistakes/minimal-mistakes@4.16.5"
minimal_mistakes_skin: "contrast"

# Site Settings
locale: "en-US"
title: &name "Ben Gohlke"
title_separator: "-"
name: *name
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of Ben Gohlke. Provides insights into tech education and
  the technology industry in general as well as tutorials, a podcast, and video-based
  training materials for breaking into tech and learning to program.
url: "https://bengohlke.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
repository: "jcgohlke/bengohlke.com"
logo: /assets/images/logo.png

search: true # false (default)
search_full_content: false # false (default)
search_provider: # lunr (default), algolia

# SEO Related
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social
twitter:
  username: "ferrousguy"
og_image: /assets/images/open-graph-default-logo.png # open graph/twitter default site image

# Analytics
analytics:
  provider: "google"
  google:
    tracking_id: UA-139312872-1
    anonymize_ip: false

# Site Author
author:
  name             : "Ben Gohlke"
  avatar           : /assets/images/author-avatar.png
  bio              : "Bicycle riding, scuba diving, junior mentoring, lego building, root beer enthusiast. I also love coding."
  location         : "Orlando, FL"
  email            :
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ferrousguy"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jcgohlke"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ferrousguy"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jcgohlke"

copyright: "COPYRIGHT © 2017-2019 BEN GOHLKE"

feed:
  path: atom.xml

  # Plugins (previously gems:)
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Collections
collections:
  tutorials:
    output: true
    permalink: /:collection/:path/
  
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _tutorials
  - scope:
      path: "_tutorials"
      type: tutorials
    values:
      layout: single
      toc: true
      toc_label: "In this lesson"
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: false
      sidebar:
        nav: "tutorials"
